FMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings
import fmsapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('fmsapp.urls', namespace='fms') )
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views

app_name = 'fmsapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index' ),
    path('administrator/login/', views.Login.as_view(), name='login'),
    path('administrator/register/', views.Register.as_view(), name='register'),
    path("dashboard/", views.Dashboard.as_view(), name="dashboard"),
    path("dashboard/logout/", views.Logout.as_view(), name="logout"),
    path("dashboard/administrator/edit/<int:pk>/", views.AccountUpdate.as_view(), name="account_update"),

   
   #Dam Routes

   path("dashboard/dam/new", views.DamNew.as_view(), name="create_dam"),
   path("dashboard/dam/", views.DamList.as_view(), name="all_dam"),
   path("dashboard/dam/<int:pk>/edit/", views.DamEdit.as_view(), name="dam_edit"),

   #Staff Path
   path("dashboard/staff/new/",views.StaffNew.as_view(), name="create_staff"),
   path("dashboard/staff/<int:pk>/single/", views.StaffSingle.as_view(), name="staff_single"),
   path("dashboard/staff/<int:pk>/edit/", views.StaffEdit.as_view(), name="staff_edit"),
   path("dashboard/staff/<int:pk>/delete/", views.StaffDestroy.as_view(), name="staff_delete"),
   path("dashboard/staff/", views.Staffers.as_view(), name="all_staff"),


   #Department Routes

   path("dashboard/department/new/",views.DepartmentNew.as_view(), name="create_dept"),
   path("dashboard/department/<int:pk>/single/",views.DepartmentDetail.as_view(), name="dept_single"),
   path("dashboard/department/<int:pk>/edit/",views.DepartmentUpdate.as_view(), name="dept_edit"),
   path("dashboard/department/<int:pk>/delete/",views.DepartmentDestroy.as_view(), name="dept_delete"),

   #Fish Routes
   path("dashboard/fish/add/",views.AddFish.as_view(), name="create_fish"),
   path("dashboard/fish/all/",views.ListFish.as_view(), name="all_fish"),
   path("dashboard/fish/<int:pk>/edit/",views.UpdateFish.as_view(), name="edit_fish"),
   path("dashboard/fish/<int:pk>/delete/",views.FishDestroy.as_view(), name="delete_fish"),

   #Harvest TimeLine
   path("dashboard/harvest/all/",views.AllHarvest.as_view(), name="harvests"),
   path("dashboard/harvest/add/",views.AddHarvest.as_view(), name="add_harvest"),
   path("dashboard/harvest/<int:pk>/edit/",views.EditHarvest.as_view(), name="edit_harvest"),
   path("dashboard/harvest/<int:pk>/delete/",views.DeleteHarvest.as_view(), name="delete_harvest"),
   path("dashboard/harvest/<int:pk>/single/",views.SingleHarvest.as_view(), name="single_harvest"),

   #Sales Routes
   path("dashboard/sales/all/",views.SalesAll.as_view(), name="sales"),
   path("dashboard/sales/add/",views.SalesAdd.as_view(), name="create_sale"),
   path("dashboard/sales/<int:pk>/edit/",views.SalesUpdate.as_view(), name="edit_sale"),
   path("dashboard/sales/<int:pk>/delete/",views.DeleteSales.as_view(), name="delete_sale"),

   #Credit Sales
   path("dashboard/credit-sales/all/",views.DebtorsAll.as_view(), name="debts"),
   path("dashboard/credit-sales/add/",views.DebtorsAdd.as_view(), name="create_debt"),
   path("dashboard/credit-sales/<int:pk>/edit/",views.DebtorsUpdate.as_view(), name="edit_debt"),
   path("dashboard/credit-sales/<int:pk>/delete/",views.DeleteDebtors.as_view(), name="delete_debt")

]

templates/fmsapp/timeline/create.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %} History and TimeLine{% endblock title %}
{% block contents %}
    <section class="row">
        <div class="col-lg-6 offset-lg-3 shadow p-4">
            <div class="card">
                <div class="card-body">
                <p class="lead text-center">New History Timeline</p><hr>
                    <form  class="form-group" method='POST' enctype='multipart/form-data'>
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-success btn-block mt-3">Submit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </section>
{% endblock contents %}

templates/fmsapp/timeline/edit.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %} Edit Harvest TimeLine{% endblock title %}
{% block contents %}
    <section class="row">
        <div class="col-lg-6 offset-lg-3">
            <div class="card">
                <div class="card-body">
                <p class="text-center lead">Update Harvest Timeline</p><hr>
                    <form action="" class="form-group" method='POST' enctype='multipart/form-data'>
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-success btn-block mt-3">Submit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </section>
{% endblock contents %}

templates/fmsapp/timeline/index.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %}
All Fishes
{% endblock title %}

{% block contents %}

  <section class="container">
    <div class=" p-3">
    </div>
    <div class="row">
      {%if timelines %}
    
     
       <div class="col-lg-12">
        <span class="title-1 m-b-25">Harvest Timeline</span> <span class="float-right"><a href="{% url 'fms:add_harvest' %}" class="btn btn-dark">Add History</a></span>
                                <div class="table-responsive table--no-card m-b-40">
                                    <table class="table table-borderless table-striped table-earning">
                                        <thead>
                                            <tr>
                                                <th>Total Harvested</th>
                                                <th>Dam</th>
                                                <th>Date</th>
                                                <th>Updated</th>
                                                <th>Manage</th>
                                            </tr>
                                        </thead>
                                        <tbody> 
                                        {% for tm in timelines  %}
                                                <tr>
                                                
                                                <td>{{tm.number |capfirst}}</td>
                                                <td>{{tm.dam}}</td>
                                                <td>{{tm.created}}</td>
                                                <td class="text-right">{{tm.updated}}</td>
                                                <td><span><a href="{% url 'fms:single_harvest' pk=tm.id %}"><i class="fas text-primary fa-eye"></i></a></span>&emsp;<span><a href="{% url 'fms:edit_harvest' pk=tm.id %}"><i class="fas text-info fa-edit"></i></a></span> &emsp; <span><a href="{% url 'fms:delete_harvest' pk=tm.id %}"><i class="fas text-danger fa-trash"></i></a></span></td>
                                            
                                            </tr>
                                        {% endfor %}    
                                        </tbody>
                                    </table>
                                </div>
      </div>
     
     

      {% else %}
      <div class='text-center'>
          <p class="display-4 ml-4 text-center text-danger">No Harvest/Sales History</p><br>
          
          <a href="{% url 'fms:add_harvest' %}" class="btn ml-4  btn-block text-center btn-outline-info">Add History</a>
      </div>
      {% endif %}
    
    </div>
  </section>

{% endblock contents  %}

templates/fmsapp/timeline/single.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %}
Harvest Timeline
{% endblock title %}

{% block contents %}

  <section class="container mt-2">

    <div class="row ml-2 mr-2">
      <div class="col-lg-8 offset-lg-2">
        <div class="card">
          <div class="card-header">
            {% comment %} <img src="{{staffer.image.url}}" width=70 height=70 class='rounded-circle img-fluid' alt=""> &nbsp; {{staffer.last_name}} - {{staffer.first_name}}
            <small> {{staffer.mobile_number}} </small>  {% endcomment %}
          </div>

          <div class="card-body">
            <ul class="list-group">
              <li class="list-group-item"><label for="fname">Total Sold</label> <span class=" float-right label">{{harvest.number | capfirst}}</span></li>
              <li class="list-group-item"><label for="fname">Dam Index:</label> <span class=" float-right label">{{harvest.dam | capfirst}}</span></li>
              <li class="list-group-item"><label for="stipend">Amount:</label> <span class=" float-right label">{{harvest.amount}}</span></li>
              <li class="list-group-item"><label for="mobile">Others:</label> <span class=" float-right label">{{harvest.others}}</span></li>
              <li class="list-group-item"><label for="state">Date and Time:</label> <span class=" float-right label">{{harvest.created | capfirst}}</span></li>
              <li class="list-group-item"><label for="country">Country:</label> <span class=" float-right label">{{harvest.updated | capfirst}}</span></li>
            </ul>
          </div>
          <div class="card-footer">
            <a href="{% url 'fms:edit_harvest' pk=harvest.id %}" class="btn btn-block btn-info">Modify</a>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock contents  %}