FMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings
import fmsapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('fmsapp.urls', namespace='fms') )
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views

app_name = 'fmsapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index' ),
    path('administrator/login/', views.Login.as_view(), name='login'),
    path('administrator/register/', views.Register.as_view(), name='register'),
    path("dashboard/", views.Dashboard.as_view(), name="dashboard"),
    path("dashboard/logout/", views.Logout.as_view(), name="logout"),
    path("dashboard/administrator/edit/<int:pk>/", views.AccountUpdate.as_view(), name="account_update"),

   
   #Dam Routes

   path("dashboard/dam/new", views.DamNew.as_view(), name="create_dam"),
   path("dashboard/dam/", views.DamList.as_view(), name="all_dam"),
   path("dashboard/dam/<int:pk>/edit/", views.DamEdit.as_view(), name="dam_edit"),

   #Staff Path
   path("dashboard/staff/new/",views.StaffNew.as_view(), name="create_staff"),
   path("dashboard/staff/<int:pk>/single/", views.StaffSingle.as_view(), name="staff_single"),
   path("dashboard/staff/<int:pk>/edit/", views.StaffEdit.as_view(), name="staff_edit"),
   path("dashboard/staff/<int:pk>/delete/", views.StaffDestroy.as_view(), name="staff_delete"),
   path("dashboard/staff/", views.Staffers.as_view(), name="all_staff"),


   #Department Routes

   path("dashboard/department/new/",views.DepartmentNew.as_view(), name="create_dept"),
   path("dashboard/department/<int:pk>/single/",views.DepartmentDetail.as_view(), name="dept_single"),
   path("dashboard/department/<int:pk>/edit/",views.DepartmentUpdate.as_view(), name="dept_edit"),
   path("dashboard/department/<int:pk>/delete/",views.DepartmentDestroy.as_view(), name="dept_delete"),

   #Fish Routes
   path("dashboard/fish/add/",views.AddFish.as_view(), name="create_fish"),
   path("dashboard/fish/all/",views.ListFish.as_view(), name="all_fish"),
   path("dashboard/fish/<int:pk>/edit/",views.UpdateFish.as_view(), name="edit_fish"),
   path("dashboard/fish/<int:pk>/delete/",views.FishDestroy.as_view(), name="delete_fish"),

   #Harvest TimeLine
   path("dashboard/harvest/all/",views.AllHarvest.as_view(), name="harvests"),
   path("dashboard/harvest/add/",views.AddHarvest.as_view(), name="add_harvest"),
   path("dashboard/harvest/<int:pk>/edit/",views.EditHarvest.as_view(), name="edit_harvest"),
   path("dashboard/harvest/<int:pk>/delete/",views.DeleteHarvest.as_view(), name="delete_harvest"),
   path("dashboard/harvest/<int:pk>/single/",views.SingleHarvest.as_view(), name="single_harvest"),

   #Sales Routes
   path("dashboard/sales/all/",views.SalesAll.as_view(), name="sales"),
   path("dashboard/sales/add/",views.SalesAdd.as_view(), name="create_sale"),
   path("dashboard/sales/<int:pk>/edit/",views.SalesUpdate.as_view(), name="edit_sale"),
   path("dashboard/sales/<int:pk>/delete/",views.DeleteSales.as_view(), name="delete_sale"),

   #Credit Sales
   path("dashboard/credit-sales/all/",views.DebtorsAll.as_view(), name="debts"),
   path("dashboard/credit-sales/add/",views.DebtorsAdd.as_view(), name="create_debt"),
   path("dashboard/credit-sales/<int:pk>/edit/",views.DebtorsUpdate.as_view(), name="edit_debt"),
   path("dashboard/credit-sales/<int:pk>/delete/",views.DeleteDebtors.as_view(), name="delete_debt")

]

templates/fmsapp/staff/create.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %} New Staffer{% endblock title %}
{% block contents %}
    <section class="row">
        <div class="col-lg-6 offset-lg-3">
            <div class="card">
                <div class="card-body">
                <p class="lead text-center">New Staffer</p><hr>
                    <form action="" class="form-group" method='POST' enctype='multipart/form-data'>
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-success btn-block mt-3">Submit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </section>
{% endblock contents %}

templates/fmsapp/staff/edit.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %} Edit Staffer{% endblock title %}
{% block contents %}
    <section class="row">
        <div class="col-lg-6 offset-lg-3">
            <div class="card">
                <div class="card-body">
                <p class="text-center lead">Update Staffer Information</p><hr>
                    <form action="" class="form-group" method='POST' enctype='multipart/form-data'>
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-success btn-block mt-3">Submit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </section>
{% endblock contents %}

templates/fmsapp/staff/index.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %}
All Staff
{% endblock title %}

{% block contents %}

  <section class="container">
    <div class=" p-3 mb-3">
      
      {% comment %} <div class=" text-center">
        <a href="{% url 'fms:create_staff' %}" class="btn btn-block btn-dark rounded"> <i class="fas fa-plus"></i> Enrol new Staff</a>
        
      </div>    {% endcomment %}
    </div>
    <div class="row">
      {%if staffs %}
     {% for staff in staffs  %}
     
       <div class="col-lg-4">
        <div class="card">
        <div class="card-header rounded-0 bg-dark">
          <p class="lead text-center">Profile and Bio</p>
        </div>
      <div class="card-body">
        <div class="mx-auto d-block">
          <img width=80 height=80 class=" rounded-circle img-fluid mx-auto d-block" src="{{staff.image.url}}" alt="{{staff.name}} image">
          <h5 class="text-sm-center mt-2 mb-1"> {{staff.first_name | capfirst}} {{staff.last_name | capfirst}} </h5>
          <div class="location text-sm-center"><i class="fa fa-map-marker"></i> {{staff.state| capfirst}}, {{staff.country|capfirst }}</div>
          <div class="location text-sm-center"><i class="fa fa-building"></i> {{staff.department| capfirst}} Department</div>
        </div>
        <hr>
      <div class="card-text">
        <strong>Work Description:</strong>
        <p>{{staff.work_description | truncatechars:40}}</p>
      </div>
      </div>
      <div class="card-footer">
        <a href="{% url 'fms:staff_single' pk=staff.id %}"><i class=" text-info fas fa-eye"></i></a> &emsp;
        <a href="{% url 'fms:staff_edit' pk=staff.id %}"><i class=" text-primary fas fa-edit"></i></a>&emsp;
        <a href="{% url 'fms:staff_delete' pk=staff.id %}"><i class=" text-danger fas fa-trash"></i></a> &emsp;
        <a href="{% url 'fms:create_staff' %}" class=""> <i class="fas fa-plus"></i> Enrol New Staff</a>
      </div>
    </div>
    </div>
     
     {% endfor %}

      {% else %}
      <div>
          <p class="display-4 ml-4 text-danger">No Staff in the Database</p><br>
          
          <a href="{% url 'fms:create_staff' %}" class="btn ml-4  btn-block text-center btn-outline-info">Add Staff</a>
      </div>
      {% endif %}
    
    </div>
  </section>

{% endblock contents  %}

templates/fmsapp/staff/single.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %}
{{staffer.first_name}} | Info
{% endblock title %}

{% block contents %}

  <section class="container mt-2">

    <div class="row ml-2 mr-2">
      <div class="col-lg-8 offset-lg-2">
        <div class="card">
          <div class="card-header">
            <img src="{{staffer.image.url}}" width=70 height=70 class='rounded-circle img-fluid' alt=""> &nbsp; {{staffer.last_name}} - {{staffer.first_name}}
            <small> {{staffer.mobile_number}} </small> 
          </div>

          <div class="card-body">
            <ul class="list-group">
              <li class="list-group-item"><label for="fname">First Name:</label> <span class=" float-right label">{{staffer.first_name | capfirst}}</span></li>
              <li class="list-group-item"><label for="fname">Last Name:</label> <span class=" float-right label">{{staffer.last_name | capfirst}}</span></li>
              <li class="list-group-item"><label for="stipend">Salary:</label> <span class=" float-right label">{{staffer.stipend}}</span></li>
              <li class="list-group-item"><label for="mobile">Mobile Number:</label> <span class=" float-right label">{{staffer.mobile_number}}</span></li>
              <li class="list-group-item"><label for="state">State:</label> <span class=" float-right label">{{staffer.state | capfirst}}</span></li>
              <li class="list-group-item"><label for="country">Country:</label> <span class=" float-right label">{{staffer.country | capfirst}}</span></li>
              <li class="list-group-item"><label for="department">Department:</label> <span class=" float-right label">{{staffer.department | capfirst}}</span></li>
              <li class="list-group-item"><label for="description">Work Decription:</label> <span class=" float-right label">{{staffer.work_description}}</span></li>
            </ul>
          </div>
          <div class="card-footer">
            <a href="{% url 'fms:staff_edit' pk=staffer.id %}" class="btn btn-block btn-info">Modify</a>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock contents  %}