FMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings
import fmsapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('fmsapp.urls', namespace='fms') )
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views

app_name = 'fmsapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index' ),
    path('administrator/login/', views.Login.as_view(), name='login'),
    path('administrator/register/', views.Register.as_view(), name='register'),
    path("dashboard/", views.Dashboard.as_view(), name="dashboard"),
    path("dashboard/logout/", views.Logout.as_view(), name="logout"),
    path("dashboard/administrator/edit/<int:pk>/", views.AccountUpdate.as_view(), name="account_update"),

   
   #Dam Routes

   path("dashboard/dam/new", views.DamNew.as_view(), name="create_dam"),
   path("dashboard/dam/", views.DamList.as_view(), name="all_dam"),
   path("dashboard/dam/<int:pk>/edit/", views.DamEdit.as_view(), name="dam_edit"),

   #Staff Path
   path("dashboard/staff/new/",views.StaffNew.as_view(), name="create_staff"),
   path("dashboard/staff/<int:pk>/single/", views.StaffSingle.as_view(), name="staff_single"),
   path("dashboard/staff/<int:pk>/edit/", views.StaffEdit.as_view(), name="staff_edit"),
   path("dashboard/staff/<int:pk>/delete/", views.StaffDestroy.as_view(), name="staff_delete"),
   path("dashboard/staff/", views.Staffers.as_view(), name="all_staff"),


   #Department Routes

   path("dashboard/department/new/",views.DepartmentNew.as_view(), name="create_dept"),
   path("dashboard/department/<int:pk>/single/",views.DepartmentDetail.as_view(), name="dept_single"),
   path("dashboard/department/<int:pk>/edit/",views.DepartmentUpdate.as_view(), name="dept_edit"),
   path("dashboard/department/<int:pk>/delete/",views.DepartmentDestroy.as_view(), name="dept_delete"),

   #Fish Routes
   path("dashboard/fish/add/",views.AddFish.as_view(), name="create_fish"),
   path("dashboard/fish/all/",views.ListFish.as_view(), name="all_fish"),
   path("dashboard/fish/<int:pk>/edit/",views.UpdateFish.as_view(), name="edit_fish"),
   path("dashboard/fish/<int:pk>/delete/",views.FishDestroy.as_view(), name="delete_fish"),

   #Harvest TimeLine
   path("dashboard/harvest/all/",views.AllHarvest.as_view(), name="harvests"),
   path("dashboard/harvest/add/",views.AddHarvest.as_view(), name="add_harvest"),
   path("dashboard/harvest/<int:pk>/edit/",views.EditHarvest.as_view(), name="edit_harvest"),
   path("dashboard/harvest/<int:pk>/delete/",views.DeleteHarvest.as_view(), name="delete_harvest"),
   path("dashboard/harvest/<int:pk>/single/",views.SingleHarvest.as_view(), name="single_harvest"),

   #Sales Routes
   path("dashboard/sales/all/",views.SalesAll.as_view(), name="sales"),
   path("dashboard/sales/add/",views.SalesAdd.as_view(), name="create_sale"),
   path("dashboard/sales/<int:pk>/edit/",views.SalesUpdate.as_view(), name="edit_sale"),
   path("dashboard/sales/<int:pk>/delete/",views.DeleteSales.as_view(), name="delete_sale"),

   #Credit Sales
   path("dashboard/credit-sales/all/",views.DebtorsAll.as_view(), name="debts"),
   path("dashboard/credit-sales/add/",views.DebtorsAdd.as_view(), name="create_debt"),
   path("dashboard/credit-sales/<int:pk>/edit/",views.DebtorsUpdate.as_view(), name="edit_debt"),
   path("dashboard/credit-sales/<int:pk>/delete/",views.DeleteDebtors.as_view(), name="delete_debt")

]

templates/fmsapp/account.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %} Edit Administrator Information{% endblock title %}
{% block contents %}
    <section class="row">
        <div class="col-lg-6 offset-lg-3">
            <div class="card">
                <div class="card-body">
                <p class="text-center lead">Update Administrator Information</p><hr>
                    <form action="" class="form-group" method='POST' enctype='multipart/form-data'>
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-success btn-block mt-3">Submit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </section>
{% endblock contents %}

templates/fmsapp/footer.html
 <div class="row">
    <div class="col-md-12">
        <div class="copyright">
            <p>Copyright © 2024 wayles digital developers courtersy of  foro<a href="https://colorlib.com">Colorlib</a>.</p>
        </div>
    </div>
</div>

templates/fmsapp/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'fmsapp/vendor/font-awesome-5/css/fontawesome-all.min.css' %}">
    <!-- Title Page-->
    <title>{% block title %}{% endblock title %}</title>

    <!-- Fontfaces CSS-->
    <link href="{% static 'fmsapp/css/font-face.css' %}" rel="stylesheet" media="all">
     <link href="{% static 'fmsapp/css/custom.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'fmsapp/vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- {% static 'fmsapp/vendor CSS-->
    <link href="{% static 'fmsapp/vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'fmsapp/css/theme.css' %}" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
    <!-- MENU SIDEBAR-->
    {% include 'fmsapp/sidebar.html' %}
    <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            {% include 'fmsapp/navbar.html' %}  
            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->
            <div class="main-content">
                {% block contents %}
                {% endblock contents %}
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="{% static 'fmsapp/vendor/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'fmsapp/vendor/bootstrap-4.1/popper.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
    <!-- {% static 'fmsapp/vendor JS       -->
    <script src="{% static 'fmsapp/vendor/slick/slick.min.js' %}">
    </script>
    <script src="{% static 'fmsapp/vendor/wow/wow.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/animsition/animsition.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}">
    </script>
    <script src="{% static 'fmsapp/vendor/counter-up/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/counter-up/jquery.counterup.min.js' %}">
    </script>
    <script src="{% static 'fmsapp/vendor/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/select2/select2.min.js' %}">
    </script>

    <!-- Main JS-->
    <script src="{% static 'fmsapp/js/main.js' %}"></script>
    {% block skript %}
    {% endblock skript %}

</body>

</html>
<!-- end document-->

templates/fmsapp/navbar.html
<header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <div></div>
                            <div class="header-button">
                               
                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">
                                            <img src="{{request.user.image.url}}" alt="{{request.session.username}}" />
                                        </div>
                                        <div class="content">
                                            {{request.session.username | upper}}
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                        <img src="{{request.user.image.url}}" alt="{{user.username}}" />
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        {{user.username | capfirst}}
                                                    </h5>
                                                    
                                                </div>
                                            </div>
                                            <div class="account-dropdown__body">
                                                <div class="account-dropdown__item">
                                                    <a href="{% url 'fmsapp:account_update' pk=user.pk %}">
                                                        <i class="zmdi zmdi-account"></i>Account</a>
                                                </div>
                                              
                                            </div>
                                            <div class="account-dropdown__footer">
                                                <a href="{% url 'fmsapp:logout' %}">
                                                    <i class="zmdi zmdi-power"></i>Logout</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

templates/fmsapp/sidebar.html
{% load static %}
<aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <img src="{% static 'fmsapp/images/icon/logo.png' %}" alt="FMS" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li class="active has-sub">
                            <a class="js-arrow" href="/dashboard">
                                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                            
                        </li>
                        <li>
                            <a href="{% url 'fms:all_dam' %}">
                                <i class="fas fa-chart-bar"></i>Dam</a>
                        </li>
                         <li class="has-sub">
                            <a class="js-arrow" href="#"><i class="far fa-copy"></i>Departments</a>
                                <a href=" {% url 'fms:create_dept' %}"> <i class="fas fa-plus"> </i> New Department</a>
                            <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                              {% for d in dept  %}
                                <li>
                                    <a href="{% url 'fms:dept_single' pk=d.id %}">{{d.name}} </a>
                                </li>
                              {% endfor %}
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'fms:all_staff' %}">
                               <i class="fas fa-user"></i>Staff / Workers</a>
                        </li>
                        <li>
                            <a href="{% url 'fms:all_fish' %}">
                                <i class="fas fa-archive"></i>Fish Record</a>
                        </li>

                         <li>
                            <a href="{% url 'fms:sales' %}">
                                <i class="far fa-folder"></i>Sales</a>
                        </li>

                        <li>
                            <a href="{% url 'fms:debts' %}">
                                <i class="fas fa-database"></i>Credit Sales</a>
                        </li>

                        <li>
                            <a href="{% url 'fms:harvests' %}">
                                <i class="fas fa-clock"></i>Harvest Timeline</a>
                        </li>
                        
                      
                    </ul>
                </nav>
            </div>
        </aside>